---
title: "Project Problem 3"
output: html_notebook
---

```{r}
#The problem we are working on is we are looking to predict house price data in King County
```

```{r}
#Our objective is to build a model to accurately predict house prices for King Country homes for Jacob Kawalski and better help him understand the local #real estate market
```

```{r}
#The data is a random sample of King County homes and their relevant sales data. This includes in total the ID, year, month, day, day of week, price, #number of bedrooms & bathrooms, the square footage of the home & lot, the number of floors of the house, whether or not the house has a waterfront  #view, the number of times the house has been viewed, the condition of the house, the grade of the house based on the King County rating scale, the #square footage of the house minus the basement & the basement itself, the year the house was built, the year the house was renovated, the zip code of #the house, the latitude and longitude of the house, and the living room area and lot size in 2015 to gauge renovations
```

```{r}
#We focused on the year the house was sold, the price as our target variable, the number of bedrooms & bathrooms, the square footage of the house & lot, #whether or not the house is a waterfront property, the grade from the King County rating scale, the year the house was built & renovated (if relevant), #the zip code, and the square footage of the living room and lot in 2015 because we felt these variables would best predict the price of a home and #correlated well with price without being too many to cause concern of over fitting the data to the model
```

```{r}
#With a low p value and an RSME which is lower in the validation set then it is in the training set, we believe that this regression model is providing us with fairly accurate predictions of the house values given our input variables.

#The predictions range from just under $200,000 to over $325,000 which from our understanding is fairly accurate for the Seattle real estate market circa 2014-15.
```

```{r}
#load in data
library(rpart)
library(rpart.plot)
library(forecast)
library(tidyr)
library(ROSE)
library(corrgram)
library(ggplot2)
library(ggpubr)
library(forecast)
house <- read.csv("house_8.csv", header = TRUE)
names(house)
```
```{r}
#examine data types
str(house)
```

```{r}
#remove empty values
house_clean <- na.omit(house)
```

```{r}
#trim down data to relevant values
house_final <- house[, -c(2,4:6, 12, 14:15, 17:18, 22:23)]
```

```{r}
#view final data types
str(house_final)
```
```{r}
set.seed(666)
#Randomly sample the rows via their indices
train_index <-sample(1:nrow(house_final), 0.6*nrow(house_final))
valid_index <-setdiff(1:nrow(house_final), train_index)

train_df <- house_final[train_index, ]
valid_df <- house_final[valid_index, ]

nrow(train_df)
nrow(valid_df)

corrgram(train_df)
```

```{r}
price_model <- lm(price ~ ., data = train_df)
summary(price_model)

# We chose to implement a multiple linear regression for our model to predict King County home prices. We chose this because regression analysis has advantages in being able to determine relative impacts of multiple variables on the target variable. The model is significant because the p value: p < .01
```

```{r}
price_model_pred <- predict(price_model, valid_df)
accuracy(price_model_pred, valid_df$price)

sd(valid_df$price)
```

```{r}
price_model_pred2 <- predict(price_model, train_df)
accuracy(price_model_pred2, train_df$price)

sd(train_df$price)

# RSME is lower in the validation data then the trainig data, which is a good indicator. Overall our model has suitable accuracy, is statistically significant, and can be validated by our RMSE values as well.
```

```{r}
# Create a new record
house <-data.frame(X =1,
                     Year =2014,
                     bedrooms =3,
                     bathrooms =1.75,
                     sqft_living =1060,
                     sqft_lot =38644,
                     waterfront =0,
                     grade =7,
                     yr_built =1983,
                     yr_renovated =0,
                     zipcode =98077,
                     sqft_living15 =1310,
                     sqft_lot15 =11416)
```

```{r}
# Create a new record
house2 <-data.frame(X =2,
                     Year =2014,
                     bedrooms =2,
                     bathrooms =1,
                     sqft_living =1220,
                     sqft_lot =5040,
                     waterfront =0,
                     grade =7,
                     yr_built =1961,
                     yr_renovated =0,
                     zipcode =98117,
                     sqft_living15 =1420,
                     sqft_lot15 =5040)
```

```{r}
# Create a new record
house3 <-data.frame(X =3,
                     Year =2014,
                     bedrooms =3,
                     bathrooms =1,
                     sqft_living =1240,
                     sqft_lot =7300,
                     waterfront =0,
                     grade =7,
                     yr_built =1968,
                     yr_renovated =0,
                     zipcode =98033,
                     sqft_living15 =1240,
                     sqft_lot15 =8260)
```

```{r}
# Predicting price of house 1
house_pred <- predict(price_model, house)

house_pred

#the price prediction for house 1 is $195,537.8
```

```{r}
# Predicting price of house 2
house2_pred <- predict(price_model, house2)

house2_pred

#the price prediction for house 2 is $325,152.3
```

```{r}
# Predicting price of house 3
house3_pred <- predict(price_model, house3)

house3_pred

#the price prediction for house 3 is $251,454.8
```


